mask208 = { 'FP1',   'FPZ',    'FP2',   'F7',     'F3',    'FZ',     'F4',     'F8', ...
    'FC5',   'FC1',    'FC2',   'FC6',    'M1',    'T7',     'C3',     'CZ', ...
    'C4',    'T8',     'M2',    'CP5',    'CP1',   'CP2',    'CP6',    'P7', ...
    'P3',    'PZ',     'P4',    'P8',     'POZ',   'O1',     'O2',     'EOG', ...
    'AF7',   'AF3',    'AF4',   'AF8',    'F5',    'F1',     'F2',     'F6',  ...
    'FC3',   'FCZ',    'FC4',   'C5',     'C1',    'C2',     'C6',     'CP3', ...
    'CP4',   'P5',     'P1',    'P2',     'P6',    'PO5',    'PO3',    'PO4', ...
    'PO6',   'FT7',    'FT8',   'TP7',    'TP8',   'PO7',    'PO8',    'OZ' };

mask210 = {  'FP1',   'FPZ',    'FP2',   'F7',     'F3',    'FZ',     'F4',     'F8', ...
    'FC5',   'FC1',    'FC2',   'FC6',    'M1',    'T7',     'C3',     'CZ', ...
    'C4',    'T8',     'M2',    'CP5',    'CP1',   'CP2',    'CP6',    'P7', ...
    'P3',    'PZ',     'P4',    'P8',     'POZ',   'O1',     'O2',     'CPZ', ...
    'AF7',   'AF3',    'AF4',   'AF8',    'F5',    'F1',     'F2',     'F6', ...
    'FC3',   'FCZ',    'FC4',   'C5',     'C1',    'C2',     'C6',     'CP3', ...
    'CP4',   'P5',     'P1',    'P2',     'P6',    'PO5',    'PO3',    'PO4', ...
    'PO6',   'FT7',    'FT8',   'TP7',    'TP8',   'PO7',    'PO8',    'OZ' };


requestMask = { 'AF3', 'AF4','F3', 'F1', 'Fz', 'F2', 'F4', 'FC3', 'FC1', 'FCz', 'FC2', 'FC4', 'C3', 'C1', 'Cz', 'C2', 'C4', 'CP3', 'CP1',  'CPz',  'CP2','CP4','P3', 'P1', 'Pz','P2', 'P4',    'PO3',  'POz',    'PO4',   'O1',     'O2' };


mask = mask210;

[isPresent, ~] = ismember(upper(mask), upper(requestMask));

tmp_string = string(int16(isPresent));

s = char(reverse(strjoin(tmp_string, '')));

d = bin2dec(char(reshape(s, 4, []).'));  % Group into 4-bit chunks and convert to decimal

% Convert to hex
hex = upper(dec2hex(d));

% Combine into one string
hex_str = join(string(hex), "");

disp('0x' + hex_str)